---
dependencies: []

galaxy_info:
  role_name: docker
  author: RicMat
  description: Docker for CentOs.
  company: "RicMat"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.4
  platforms:
    - name: Centos
      versions:
        - 7
        - 8
  galaxy_tags: []
